# Generated by Django 5.2.7 on 2025-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_product_final_price_after_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='in_carts', to='products.product'),
        ),
    ]
