# Generated by Django 5.2.7 on 2025-10-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price_after_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price including tax', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_before_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price before tax is applied', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='store_type',
            field=models.CharField(choices=[('tech', 'Technology'), ('fashion', 'Fashion'), ('grocery', 'Grocery'), ('general', 'General'), ('electronics', 'Electronics'), ('home', 'Home & Garden'), ('sports', 'Sports'), ('books', 'Books'), ('other', 'Other')], db_index=True, default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original scraped price', max_digits=10, null=True),
        ),
    ]
